### PR TITLE
Removed unused include

### PR DESCRIPTION
**Pull request by tmaltesen**

### CODE REVIEW

**Comment by hnhoan** [comment]
Thanks very much for the continuous integration apps suggestion.  Hope to be able to do that in the future.

**Comment by tmaltesen** [comment]
I decided to give it another try since I kept on struggling with the nRF SDK functions.

So I made a clean project and figured out what was needed for it to compile and build.

Now I’m testing real use, currently not able to transmit, but debugging….

Best regards,
Thomas

Fra: hnhoan <notifications@github.com>
Sendt: 22. oktober 2019 14:35
Til: IOsonata/IOsonata <IOsonata@noreply.github.com>
Cc: Thomas Maltesen <tm@prolon.dk>; Author <author@noreply.github.com>
Emne: Re: [IOsonata/IOsonata] Removed unused include (#5)


Thanks very much for the continuous integration apps suggestion. Hope to be able to do that in the future.

**Comment by tmaltesen** [comment]
Strange, I do not see anything on the serial port.
Checking register pin mapping and more I see no difference if comparing to a running application.

Any hints? (what can I look for).

I did check UARTE register setting, pin numbers seems OK. Figured out I had to set the GPIO myself so added:

      nrf_gpio_pin_set(TX_PIN);
      nrf_gpio_cfg_output(TX_PIN);
      nrf_gpio_cfg_input(RX_PIN, NRF_GPIO_PIN_NOPULL);

Still no data on serial line.


/Thomas

Fra: hnhoan <notifications@github.com>
Sendt: 22. oktober 2019 14:35
Til: IOsonata/IOsonata <IOsonata@noreply.github.com>
Cc: Thomas Maltesen <tm@prolon.dk>; Author <author@noreply.github.com>
Emne: Re: [IOsonata/IOsonata] Removed unused include (#5)


Thanks very much for the continuous integration apps suggestion. Hope to be able to do that in the future.

**Comment by hnhoan** [comment]
There is a pin config that you need to set it into the config.  It is then handled automatically in the driver.  
see the uart examples in IOsonata/exemples/uart
It should goes like this

```
static IOPINCFG s_UartPins[] = {
	{UART_RX_PORT, UART_RX_PIN, UART_RX_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},	// RX
	{UART_TX_PORT, UART_TX_PIN, UART_TX_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},	// TX
	//{UART_CTS_PORT, UART_CTS_PIN, UART_CTS_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},	// CTS
	//{UART_RTS_PORT, UART_RTS_PIN, UART_RTS_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},// RTS
};

// UART configuration data
const UARTCFG g_UartCfg = {
	.DevNo = UART_NO,
	.pIOPinMap = s_UartPins,
	.NbIOPins = sizeof(s_UartPins) / sizeof(IOPINCFG),
...

```

**Comment by tmaltesen** [comment]
Thanks for the advise. This is what I did, but it seems something is missing.

Only thing differs is that I put the UART_RX_PINOP/ UART_TX_PINOP as -1 since it was undefined and I could not see it in use.

static IOPINCFG s_UartPins0[] = {
                             {NRF_PORT(RX1_PIN_NUMBER), NRF_PIN(RX1_PIN_NUMBER), -1, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},             // RX
                             {NRF_PORT(TX1_PIN_NUMBER), NRF_PIN(TX1_PIN_NUMBER), -1, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL}   // TX
};


/Thomas

Fra: hnhoan <notifications@github.com>
Sendt: 22. oktober 2019 16:00
Til: IOsonata/IOsonata <IOsonata@noreply.github.com>
Cc: Thomas Maltesen <tm@prolon.dk>; Author <author@noreply.github.com>
Emne: Re: [IOsonata/IOsonata] Removed unused include (#5)


There is a pin config that you need to set it into the config. It is then handled automatically in the driver.
see the uart examples in IOsonata/exemples/uart
It should goes like this

static IOPINCFG s_UartPins[] = {

        {UART_RX_PORT, UART_RX_PIN, UART_RX_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},     // RX

        {UART_TX_PORT, UART_TX_PIN, UART_TX_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},     // TX

        //{UART_CTS_PORT, UART_CTS_PIN, UART_CTS_PINOP, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},     // CTS

        //{UART_RTS_PORT, UART_RTS_PIN, UART_RTS_PINOP, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},// RTS

};



// UART configuration data

const UARTCFG g_UartCfg = {

        .DevNo = UART_NO,

        .pIOPinMap = s_UartPins,

        .NbIOPins = sizeof(s_UartPins) / sizeof(IOPINCFG),

...

**Comment by hnhoan** [comment]
PinOp is not used in nRF series.  It shouldn't affect but if you put PortNo or PinNo to -1, it will ignore the pin configuration.  Do you have a Preprocessor define NRF52840_XXAA defined ? It is required to define the target for the nrf.h to load the correct includes

**Comment by tmaltesen** [comment]
Preprocessor for NRF52840_XXAA is defined.
And port and pin are correctly configured.

I will step through initialization and see what I can find.

/Thomas

Fra: hnhoan <notifications@github.com>
Sendt: 22. oktober 2019 16:10
Til: IOsonata/IOsonata <IOsonata@noreply.github.com>
Cc: Thomas Maltesen <tm@prolon.dk>; Author <author@noreply.github.com>
Emne: Re: [IOsonata/IOsonata] Removed unused include (#5)


PinOp is not used in nRF series. It shouldn't affect but if you put PortNo or PinNo to -1, it will ignore the pin configuration. Do you have a Preprocessor define NRF52840_XXAA defined ? It is required to define the target for the nrf.h to load the correct includes

**Comment by tmaltesen** [comment]
I’m using the following configuration:

static IOPINCFG s_UartPins1[] = {
                             {NRF_PORT(RX2_PIN_NUMBER), NRF_PIN(RX2_PIN_NUMBER), -1, IOPINDIR_INPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},                // RX
                             {NRF_PORT(TX2_PIN_NUMBER), NRF_PIN(TX2_PIN_NUMBER), -1, IOPINDIR_OUTPUT, IOPINRES_NONE, IOPINTYPE_NORMAL},                      // TX
};

uint8_t txBuff[SERIAL_INTERFACE_COUNT][FIFOSIZE];

const UARTCFG uartCfg[SERIAL_INTERFACE_COUNT] = {
{
      .DevNo = 1,
      .pIOPinMap = s_UartPins1,
      .NbIOPins = sizeof(s_UartPins1) / sizeof(IOPINCFG),
      .Rate = 9600,
      .DataBits = 8,
      .Parity = UART_PARITY_NONE,
      .StopBits = 1,
      .FlowControl = UART_FLWCTRL_NONE,
      .bIntMode = true,
      .IntPrio = 1,
      .EvtCallback = SerialInterfaceEventHandler,
      .bFifoBlocking = true,
      .RxMemSize = 0,
      .pRxMem = NULL,
      .TxMemSize = FIFOSIZE,
      .pTxMem = txBuff[1],
      .bDMAMode = false



Fra: hnhoan <notifications@github.com>
Sendt: 22. oktober 2019 16:10
Til: IOsonata/IOsonata <IOsonata@noreply.github.com>
Cc: Thomas Maltesen <tm@prolon.dk>; Author <author@noreply.github.com>
Emne: Re: [IOsonata/IOsonata] Removed unused include (#5)


PinOp is not used in nRF series. It shouldn't affect but if you put PortNo or PinNo to -1, it will ignore the pin configuration. Do you have a Preprocessor define NRF52840_XXAA defined ? It is required to define the target for the nrf.h to load the correct includes

**Comment by hnhoan** [comment]
Special pins to check. 0.18 is reset pin, 0.09 & 0.10 are for NFC by default unless you reconfigured them as gpio

**Comment by tmaltesen** [comment]
Found the problem, it was not related to your code.

I had a pin declaration that I changed when converting from nrfx to iosonata so it was initialized with a wrong value.

/Thomas

Fra: hnhoan <notifications@github.com>
Sendt: 22. oktober 2019 16:36
Til: IOsonata/IOsonata <IOsonata@noreply.github.com>
Cc: Thomas Maltesen <tm@prolon.dk>; Author <author@noreply.github.com>
Emne: Re: [IOsonata/IOsonata] Removed unused include (#5)


Special pins to check. 0.18 is reset pin, 0.09 & 0.10 are for NFC by default unless you reconfigured them as gpio

**Comment by tmaltesen** [comment]
I seems that on roughly 10% of the transmissions, the event UART_EVT_TXREADY is fired before the data has actually been transmitted. Seems to happen pretty early like when 3-4 bytes are still in queue.

Have I misunderstood the function of UART_EVT_TXREADY? As the name implies it could look like there is space in the transmitter not that it is actually empty.

I need an event when data HAS BEEN transmitted on the wire. It is because I am using RS485 and use the signal to disable the transmitter.


Best regards,
Thomas

Fra: hnhoan <notifications@github.com>
Sendt: 22. oktober 2019 16:36
Til: IOsonata/IOsonata <IOsonata@noreply.github.com>
Cc: Thomas Maltesen <tm@prolon.dk>; Author <author@noreply.github.com>
Emne: Re: [IOsonata/IOsonata] Removed unused include (#5)


Special pins to check. 0.18 is reset pin, 0.09 & 0.10 are for NFC by default unless you reconfigured them as gpio

**Comment by tmaltesen** [comment]
It seems that around line 268-295 you actually check the queue, but you fire the event even if you just previously set the flag bTxReady to false (line 284).

/Thomas

Fra: hnhoan <notifications@github.com>
Sendt: 22. oktober 2019 16:36
Til: IOsonata/IOsonata <IOsonata@noreply.github.com>
Cc: Thomas Maltesen <tm@prolon.dk>; Author <author@noreply.github.com>
Emne: Re: [IOsonata/IOsonata] Removed unused include (#5)


Special pins to check. 0.18 is reset pin, 0.09 & 0.10 are for NFC by default unless you reconfigured them as gpio

**Comment by hnhoan** [comment]
here is how you can achieve switching between RX/TX mode in RS-485.
in the TXREADY event
```
	case UART_EVT_TXREADY:
			cnt = CFifoUsed(pDev->hTxFifo);
			if (cnt == 0 && pDev->bTxReady == true)
			{
				usDelay(100);
				IOPinClear(vTxEnPin.PortNo, vTxEnPin.PinNo);
			}

```

**Comment by hnhoan** [comment]
The flag TXREADY is to indicate the state of the hardware UART that has sent to hardware fifo. It's the interrupt state.  This is to allows you to continuous queuing more data at max speed when the queue is full. It is useful in treating mode.

**Comment by tmaltesen** [comment]
Thank you very much for the response.

Why do you need a delay? If it is because the event occurs before the last byte is transmitted the delay will be baudrate sensitive.

/Thomas

Fra: hnhoan <notifications@github.com>
Sendt: 22. oktober 2019 17:50
Til: IOsonata/IOsonata <IOsonata@noreply.github.com>
Cc: Thomas Maltesen <tm@prolon.dk>; Author <author@noreply.github.com>
Emne: Re: [IOsonata/IOsonata] Removed unused include (#5)


here is how you can achieve switching between RX/TX mode in RS-485.
in the TXREADY event

        case UART_EVT_TXREADY:

                       cnt = CFifoUsed(pDev->hTxFifo);

                       if (cnt == 0 && pDev->bTxReady == true)

                       {

                               usDelay(100);

                               IOPinClear(vTxEnPin.PortNo, vTxEnPin.PinNo);

                       }

**Comment by tmaltesen** [comment]
It seems fine even without the delay. Thanks a lot!

Fra: hnhoan <notifications@github.com>
Sendt: 22. oktober 2019 17:50
Til: IOsonata/IOsonata <IOsonata@noreply.github.com>
Cc: Thomas Maltesen <tm@prolon.dk>; Author <author@noreply.github.com>
Emne: Re: [IOsonata/IOsonata] Removed unused include (#5)


here is how you can achieve switching between RX/TX mode in RS-485.
in the TXREADY event

        case UART_EVT_TXREADY:

                       cnt = CFifoUsed(pDev->hTxFifo);

                       if (cnt == 0 && pDev->bTxReady == true)

                       {

                               usDelay(100);

                               IOPinClear(vTxEnPin.PortNo, vTxEnPin.PinNo);

                       }

**Pull request merged**
